name: consumer deployment

on: workflow_dispatch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
#     https://docs.pact.io/pact_broker/can_i_deploy
    - name: Check Compatibility
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        run: |
          pact-broker can-i-deploy \
          --broker-base-url ${{ vars.PACT_BROKER_BASE_URL }} \
          --broker-token ${{ secrets.PACT_BROKER_TOKEN }} \
          --pacticipant consumer \
          --version ${{ github.sha }} \
          --to-environment production
    - name: Deploy
      run: echo 'Deployed'
#     https://docs.pact.io/pact_broker/recording_deployments_and_releases#recording-releases
    - name: Record Release
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        run: |
          pact-broker record-release \
          --broker-base-url ${{ vars.PACT_BROKER_BASE_URL }} \
          --broker-token ${{ secrets.PACT_BROKER_TOKEN }} \
          --pacticipant consumer \
          --version ${{ github.sha }} \
          --environment production
