name: consumer release recorder

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Toggle version'
        required: true
        type: string

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
#     https://docs.pact.io/pact_broker/recording_deployments_and_releases#recording-releases
    - name: Record Release
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -e PACT_BROKER_BASE_URL=${{ vars.PACT_BROKER_BASE_URL }} -e PACT_BROKER_TOKEN=${{ secrets.PACT_BROKER_TOKEN }}
        run: |
          pact-broker record-release \
          --pacticipant consumer \
          --version ${{ inputs.version }} \
          --environment production
