name: consumer build

on:
  push:
    branches:
    - main
    paths:
     - '**/consumer/**'
     - '**/consumer-builder.yml'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test base
      run: ./consumer/gradlew clean test -p ./consumer -DincludeTags=base
    - name: Publish Pacts
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -v ${{ github.workspace }}:${{ github.workspace }} -e PACT_BROKER_BASE_URL=${{ vars.PACT_BROKER_BASE_URL }} -e PACT_BROKER_TOKEN=${{ secrets.PACT_BROKER_TOKEN }}
        run: |
          if [-f ${{ github.workspace }}/consumer/build/pacts]; then
            pact-broker publish ${{ github.workspace }}/consumer/build/pacts \
            --consumer-app-version ${{ github.sha }} \
            --branch ${{ github.ref_name }}
          fi
    - name: Test feature
      run: ./consumer/gradlew clean test -p ./consumer -DincludeTags=feature.customer
    - name: Publish Pacts
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -v ${{ github.workspace }}:${{ github.workspace }} -e PACT_BROKER_BASE_URL=${{ vars.PACT_BROKER_BASE_URL }} -e PACT_BROKER_TOKEN=${{ secrets.PACT_BROKER_TOKEN }}
        run: |
          pact-broker publish ${{ github.workspace }}/consumer/build/pacts \
          --consumer-app-version ${{ github.sha }}+feature.customer \
          --branch ${{ github.ref_name }}
    - name: Verify Pacts
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'provider-pact-verifier.yml',
            ref: context.ref
          })
