name: CI Consumer

on:
  push:
    branches:
    - main
    paths:
     - '**/consumer/**'
     - '**/consumer.yml'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test Consumer
      run: ./consumer/gradlew clean test -p ./consumer
    - name: Publish Pacts
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -v ${{ github.workspace }}:/work -e PACT_BROKER_BASE_URL=https://stastest.pactflow.io/ -e PACT_BROKER_TOKEN=4CJtjKMtAFlAbj2sqawKpQ
        run: pact-broker publish /work/consumer/build/pacts --consumer-app-version ${{ github.sha }} --branch ${{ github.ref_name }}
    - name: Verify Pacts
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'provider-pact-verifier.yml',
            ref: context.ref
          })
    - name: Release Consumer
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -e PACT_BROKER_BASE_URL=https://stastest.pactflow.io/ -e PACT_BROKER_TOKEN=4CJtjKMtAFlAbj2sqawKpQ
        run: pact-broker record-release --pacticipant consumer --version ${{ github.sha }} --environment production
