name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Consumer
      run: ./consumer/gradlew clean build -p ./consumer
    - name: Publish Pacts
      run: ./consumer/gradlew pactPublish -p ./consumer -Dpact.publish.consumer.branchName=${{ github.ref_name }} -Dpact.publish.consumer.version=${{ github.sha }}
    - name: Build Provider
      run: ./provider/mvnw clean test -f ./provider -Dpact.verifier.publishResults=true -Dpact.provider.branchName=main -Dpact.provider.version=0.0.1
