name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Consumer
      run: ./consumer/gradlew clean build -p ./consumer
    - name: Publish Pacts
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -v ${{ github.workspace }}:/work -e PACT_BROKER_BASE_URL=https://stastest.pactflow.io/ -e PACT_BROKER_TOKEN=4CJtjKMtAFlAbj2sqawKpQ
        run: pact-broker publish /work/consumer/build/pacts --consumer-app-version ${{ github.sha }} --branch ${{ github.ref_name }}
    - name: Build Provider
      run: ./provider/mvnw clean test -f ./provider -Dpact.verifier.publishResults=true -Dpact.provider.branch=${{ github.ref_name }} -Dpact.provider.version=${{ github.sha }}
    - name: Release Consumer
      uses: addnab/docker-run-action@v3
      with:
        image: pactfoundation/pact-cli:0.56.0.6
        options: -e PACT_BROKER_BASE_URL=https://stastest.pactflow.io/ -e PACT_BROKER_TOKEN=4CJtjKMtAFlAbj2sqawKpQ
        run: pact-broker record-release --pacticipant consumer --version ${{ github.sha }} --environment production
