name: provider pact verification

on: workflow_dispatch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: benjlevesque/short-sha@v2.2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test Provider
# TODO verify only the changed pact
      run: |
        ./provider/mvnw clean test -f ./provider \
        -Dpactbroker.url=${{ vars.PACT_BROKER_BASE_URL }} \
        -Dpactbroker.auth.token=${{ secrets.PACT_BROKER_TOKEN }} \
        -Dpactbroker.providerBranch=${{ github.ref_name }} \
        -Dpact.verifier.publishResults=true \
        -Dpact.provider.branch=${{ github.ref_name }} \
        -Dpact.provider.version=${{ env.SHA }}
